version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: rafaelgurgel/udacity-reverseproxy:${SHA:-latest} 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: rafaelgurgel/udacity-restapi-user:${SHA:-latest}
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: rafaelgurgel/udacity-restapi-feed:${SHA:-latest}
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: rafaelgurgel/udacity-frontend:${SHA:-latest}
